### ISSUE TITLE
移动端适配新方法

### ISSUE THREAD

**Issue by wswmsword** [chao921125/vue-vite#134]
hc precog 你好，看了你的 README 对于移动端适配的介绍，应该是全面的，但可能有点主观，比如媒体查询的适配，这应该还是主流，我认为这也是所有方法里对用户最友好，且只需要有前端介入的方法。
对于移动端适配，比较多的是 `vw` 和 `rem`，前者一直有个“大屏大字”的问题，后者可以通过监听屏幕宽度限制根元素字体大小解决，所以我想给你推荐我写的插件，这个插件可以弥补 `vw` 出现的大屏大字问题，达到和 rem 一样的，在宽屏可访问的效果，插件是 [postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)。

**Comment by wswmsword** [comment]
是啊，结合实际业务即可，不过过分强调业务范围，就像是在预测用户行为，不是很可靠，就比如我经常从移动端复制链接到桌面端，最后就是得打开 F12 才能访问。
你说的 vw 结合 rem 的情况我没理解，能简单解释下吗？

**Comment by chao921125** [comment]
绕不开的媒体查询，就像你插件中解决最大最小限制的一样，不过rem+媒体查询基本上够用，vw+vh的方案也很不错哈哈，看选择吧。
可以参考下这个文章下哈：https://blog.csdn.net/qq_35546787/article/details/107635368。

**Comment by wswmsword** [comment]
大概理解了，是说 rem+媒体查询用来适配字体尺寸，vw 用来适配非字体的其它尺寸的意思吧
